
namespace ModAPI
{
    public enum LayerMasksEnum
    {
        Default,
        TransparentFX,
        IgnoreRaycast,
        Layer3,
        Water,
        UI,
        Layer6,
        Layer7,
        Road,
        HingedObjects,
        Terrain,
        DontCollide,
        Bolts,
        Dashboard,
        GUI,
        Tools,
        Wheel,
        Collider,
        Datsun,
        Parts,
        Player,
        Lifter,
        Collider2,
        PlayerOnlyColl,
        Cloud,
        Glass,
        Forest,
        NoRain,
        TriggerOnly,
        Layer29,
        Layer30,
        Layer31,
    }
}
